name: Build and Publish Debian Package

on:
  push:
    tags:
      - 'v*'
      - 'release-*'

jobs:
  build-deb-and-release:
    runs-on: ubuntu-22.04
    steps:
      # 1) Check out code with full history to include tags
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history including tags

      # 2) Set up Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      # 3) Install packaging tools (NFPM, etc.)
      - name: Install Tools
        run: make install-tools

      # 4) Build the .deb packages without GPG signing
      - name: Build Packages
        run: |
          # Build packages without requiring GPG signing
          # NFPM_SIGNING_KEY_FILE is left unset to skip signing in nfpm
          make package
        env:
          NFPM_SIGNING_KEY_FILE: ""  # Explicitly unset to avoid GPG requirement

      # 5) Upload the .deb to the "Actions" tab as an artifact (optional)
      - name: Upload .deb artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: deb-artifact
          path: ./build/github/packaging/*.deb

      # 6) Attach the .deb to the GitHub Release
      - name: Upload to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/github/packaging/*.deb
          file_glob: true
          tag: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          overwrite: true
          prerelease: false