name: Build Debian Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up GPG
      run: |
        # Create GPG key configuration
        cat > key-config <<EOF
        %echo Generating GPG key
        Key-Type: RSA
        Key-Length: 4096
        Name-Real: Your Name
        Name-Email: your.email@example.com
        Expire-Date: 1y
        %no-protection
        %commit
        %echo Done
        EOF
        
        # Generate new GPG key
        gpg --batch --generate-key key-config
        
        # Export the key ID
        export GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | cut -d'/' -f2 | cut -d' ' -f1)
        echo "GPG_KEY_ID=$GPG_KEY_ID" >> $GITHUB_ENV
        
        # Export public and private keys
        gpg --armor --export $GPG_KEY_ID > public.key
        gpg --armor --export-secret-key $GPG_KEY_ID > private.key

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper dh-make

    - name: Setup Debian packaging
      run: |
        # Create debian directory if it doesn't exist
        mkdir -p debian
        
        # Create debian/changelog
        cat > debian/changelog <<EOF
        mypackage (1.0.0-1) unstable; urgency=medium

          * Initial release
          * Add your changes here

         -- Your Name <your.email@example.com>  $(date -R)
        EOF
        
        # Create debian/control
        cat > debian/control <<EOF
        Source: mypackage
        Section: utils
        Priority: optional
        Maintainer: Your Name <your.email@example.com>
        Build-Depends: debhelper-compat (= 13)
        Standards-Version: 4.5.1

        Package: mypackage
        Architecture: any
        Depends: \${shlibs:Depends}, \${misc:Depends}
        Description: My Package Description
         A longer description of your package
         spanning multiple lines.
        EOF
        
        # Create debian/rules (using printf to preserve tabs)
        printf '#!/usr/bin/make -f\n%%:\n\tdh $@\n' > debian/rules
        chmod +x debian/rules
        
        # Create debian/compat
        echo "13" > debian/compat

    - name: Build package
      run: |
        # Import the signing key
        gpg --import private.key
        
        # Build the package
        dpkg-buildpackage -us -uc
        
        # Sign the package
        dpkg-sig --sign builder -k $GPG_KEY_ID ../*.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: ../*.deb
        retention-days: 5

    - name: Cleanup sensitive data
      if: always()
      run: |
        rm -f private.key public.key key-config
        gpg --batch --yes --delete-secret-keys $GPG_KEY_ID
        gpg --batch --yes --delete-key $GPG_KEY_ID